#! /bin/sh

set -eu

if ! test -d .git
then
  echo "run from source root."
  exit 1
fi

verbose=0
while getopts 'v' opt
do
  case $opt in
    v) verbose=1 ;;
  esac
done

shift $((OPTIND-1))

fail () {
  echo fail
  exit 1
}

pass () {
  echo pass
}

for t in ./test/*.test
do  
  echo -n "$(basename $t) ... "
  if test $verbose = 1
  then
    echo
    ./test/run-one $t || fail
  else
    ./test/run-one $t > /dev/null 2>&1 || fail
  fi
  pass
done
