#! /bin/sh

set -eu

if ! test -d .git
then
  echo "run from source root."
  exit 1
fi

source_root="$(pwd)"
export PATH="$source_root/src:$PATH"
scratch="$(mktemp -d)"

finish () {
  rm -rf "$scratch"
}
trap finish EXIT

t=$(realpath $1)
cd $scratch
set +e
$t
result="$?"
cd $source_root
exit "$result"

