#! /bin/sh

set -eu

if ! test -d .git
then
  echo "run from source root."
  exit 1
fi

fail () {
  echo fail
  exit 1
}

pass () {
  echo pass
}

for t in ./test/*.test
do  
  echo -n "$(basename $t) ... "
  tmpfile="$(mktemp)"
  exec 3>"$tmpfile"
  exec 4<"$tmpfile"
  rm "$tmpfile"
  if ! ./test/run-one $t >&3 /dev/null 2>&1
  then
    echo -e "\nTest log:"
    cat <&4
    fail
  fi
  pass
done
