#! /bin/sh
set -eu

usage () {
  echo "path-fspec [-r root] [-a] [PATH]"
  exit 1
}

root=""
absolute=0

while getopts 'har:' opt
do
  case $opt in
    a) absolute=1 ;;
    r) root=$OPTARG ;;
    h) usage ;;
  esac
done

shift $((OPTIND-1))

cd ${1:-.}

find . -not -name "." | cut -c 3- | while read f
do
  echo "$root$f"
  # We must check for link first.
  if test -L "$f"
  then
    echo "type=sym"
    echo "link=$(readlink $f)"
  elif test -f "$f"
  then
    echo "type=reg"
    stat "$f" --printf="mode=%a\n"
    if test "$absolute" = 1
    then
      echo "source=$(realpath $f)"
    fi
  elif test -d "$f"
  then
    echo "type=dir"
    stat "$f" --printf="mode=%a\n"
  else
    echo "unsupported file type at $f" >&2
    exit 1
  fi
  echo ""
done
